# Generated by Django 4.1 on 2022-08-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0004_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
