# Generated by Django 4.1 on 2022-08-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0005_remove_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
